<?php

namespace DoctrineORMModule\Proxy\__CG__\Biblioteca\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Usuario extends \Biblioteca\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setAtivo($ativo)
    {
        $this->__load();
        return parent::setAtivo($ativo);
    }

    public function getAtivo()
    {
        $this->__load();
        return parent::getAtivo();
    }

    public function setChaveAtivacao($chaveAtivacao)
    {
        $this->__load();
        return parent::setChaveAtivacao($chaveAtivacao);
    }

    public function getChaveAtivacao()
    {
        $this->__load();
        return parent::getChaveAtivacao();
    }

    public function setDataCriacao($dataCriacao)
    {
        $this->__load();
        return parent::setDataCriacao($dataCriacao);
    }

    public function getDataCriacao()
    {
        $this->__load();
        return parent::getDataCriacao();
    }

    public function setDoutrinaid($doutrinaid)
    {
        $this->__load();
        return parent::setDoutrinaid($doutrinaid);
    }

    public function getDoutrinaid()
    {
        $this->__load();
        return parent::getDoutrinaid();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIgreja($igreja)
    {
        $this->__load();
        return parent::setIgreja($igreja);
    }

    public function getIgreja()
    {
        $this->__load();
        return parent::getIgreja();
    }

    public function setLogin($login)
    {
        $this->__load();
        return parent::setLogin($login);
    }

    public function getLogin()
    {
        $this->__load();
        return parent::getLogin();
    }

    public function setNomeCompleto($nomeCompleto)
    {
        $this->__load();
        return parent::setNomeCompleto($nomeCompleto);
    }

    public function getNomeCompleto()
    {
        $this->__load();
        return parent::getNomeCompleto();
    }

    public function setPublicacoes($publicacoes)
    {
        $this->__load();
        return parent::setPublicacoes($publicacoes);
    }

    public function getPublicacoes()
    {
        $this->__load();
        return parent::getPublicacoes();
    }

    public function setSenha($senha)
    {
        $this->__load();
        return parent::setSenha($senha);
    }

    public function getSenha()
    {
        $this->__load();
        return parent::getSenha();
    }

    public function setSrcImagem($srcImagem)
    {
        $this->__load();
        return parent::setSrcImagem($srcImagem);
    }

    public function getSrcImagem()
    {
        $this->__load();
        return parent::getSrcImagem();
    }

    public function setTag($tag)
    {
        $this->__load();
        return parent::setTag($tag);
    }

    public function getTag()
    {
        $this->__load();
        return parent::getTag();
    }

    public function hydrate(array $data)
    {
        $this->__load();
        return parent::hydrate($data);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'tag', 'nomeCompleto', 'srcImagem', 'email', 'login', 'senha', 'igreja', 'chaveAtivacao', 'dataCriacao', 'ativo', 'doutrinaid');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}