<section id="head">
    <section id="filter-block" xmlns="http://www.w3.org/1999/html">
        <div class="filter">
            <label for="fullname">Fullname: </label>
            <input name="fullname" id="fullname" type="text" />
        </div>
        <div id="filter-buttons">
            <button id="btnFilter" class="btn">Filter</button>
            <button id="btnClear" class="btn btn-danger">Clear</button>
        </div>
    </section>
    <section id="action-user">
        <div id="insert-user">
            <button class="btn btn-primary">Insert a User</button>
        </div>
    </section>
</section>
<section id="table">
    <table class="table" id="datatable">
        <thead class="lines2">
        <tr>
            <th>Fullname</th>
            <th>E-mail</th>
            <th>Created at</th>
            <th>Actived</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td colspan="7" class="dataTables_empty">Loading...</td>
        </tr>
        </tbody>
    </table>
</section>