<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Access</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Access ZF2 Module">
        <meta name="author" content="Tássio de Oliveira Silva Auad">
        <link href="/css/bootstrap/bootstrap.css" rel="stylesheet">
        <link href="/css/bootstrap/bootstrap-responsive.css" rel="stylesheet">
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <body>
        <div class="navbar navbar-inverse" style="position: static;">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">Access</a>
                    <div class="nav-collapse collapse navbar-inverse-collapse">
                        <ul class="nav pull-right">
                            <li><a href="#">Sign In</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="#">Create Account</a></li>
                            <li class="divider-vertical"></li>
                            <li><a href="#">Forgot your password?</a></li>
                        </ul>
                    </div><!-- /.nav-collapse -->
                </div>
            </div><!-- /navbar-inner -->
        </div><!-- /navbar -->
        </div>
        <?php echo $this->content; ?>
        <footer id="copyright">
            <p>&copy; Access 2012</p>
        </footer>
    </body>
</html>
