<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Access</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Access ZF2 Module">
        <meta name="author" content="Tássio de Oliveira Silva Auad">
        <link href="/css/bootstrap/bootstrap.css" rel="stylesheet">
        <link href="/css/bootstrap/bootstrap-responsive.css" rel="stylesheet">
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <body>
        <div class="navbar navbar-inverse" style="position: static;">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="#">Access</a>
                    <div class="nav-collapse collapse navbar-inverse-collapse">
                        <?php echo $this->navigation('navigation')->menu()->setUlClass('nav pull-right') ?>
                    </div>
                </div>
            </div>
        </div>

        <?php
            if($this->messenger()->hasMessages()):
                if($this->messenger()->hasMessages(Messenger\Helper\MessengerHelper::ERRO)):
        ?>
        <div id="messages" class="alert alert-error">
            <?php echo $this->messenger()->getMessagesAsString(Messenger\Helper\MessengerHelper::ERRO); ?>
        </div>
        <?php
                endif;
                if($this->messenger()->hasMessages(Messenger\Helper\MessengerHelper::SUCESSO)):
        ?>
        <div id="messages" class="alert alert-success">
            <?php echo $this->messenger()->getMessagesAsString(Messenger\Helper\MessengerHelper::SUCESSO); ?>
        </div>
        <?php
                endif;
            endif;
        ?>

        <?php echo $this->content; ?>
    </body>
</html>
