<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Access</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Access ZF2 Module">
        <meta name="author" content="Tássio de Oliveira Silva Auad">
        <link href="/css/bootstrap/bootstrap.css" rel="stylesheet">
        <link href="/css/layout.css" rel="stylesheet">
        <link href="/css/bootstrap/bootstrap-responsive.css" rel="stylesheet">
        <script src="/js/jquery-1.8.0.min.js"></script>
        <script src="/js/jquery-ui.js"></script>
        <script src="/js/bootstrap.js"></script>
        <script src="/js/bootstrap-button.js"></script>
        <script src="/js/bootstrap-dropdown.js"></script>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <body>
        <div id="main-menu" class="navbar navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="#">Access</a>
                    <?php
                    $loggedUser = $this->access()->getUser();
                    if(!empty($loggedUser)):
                    ?>
                    <div id="user" class="nav-collapse collapse navbar-collapse">
                        <ul class="nav pull-left">
                            <li><img id="user-photo" class="img-circle" src='<?= $this->access()->getUser()->getPhoto(); ?>' /><a><?=$this->access()->getUser()->getFullname(); ?></a></li>
                        </ul>
                    </div>
                    <?php endif; ?>
                    <div id="main-menu" class="nav-collapse collapse navbar-inverse-collapse">
                        <?php echo $this->navigation('navigation')->menu()->setUlClass('nav pull-right') ?>
                    </div>
                </div>
            </div>
        </div>

        <?php
            if($this->messenger()->hasMessages()):
                if($this->messenger()->hasMessages(Messenger\Helper\MessengerHelper::ERRO)):
        ?>
        <div id="messages" class="alert alert-error">
            <p class="message">
                <?php echo $this->messenger()->getMessagesAsString(Messenger\Helper\MessengerHelper::ERRO); ?>
            </p>
        </div>
        <?php
                endif;
                if($this->messenger()->hasMessages(Messenger\Helper\MessengerHelper::SUCESSO)):
        ?>
        <div id="messages" class="alert alert-success">
            <p class="message">
                <?php echo $this->messenger()->getMessagesAsString(Messenger\Helper\MessengerHelper::SUCESSO); ?>
            </p>
        </div>
        <?php
                endif;
            endif;
        ?>

        <?php echo $this->content; ?>

        <!-- Le javascript -->
        <script src="/js/bootstrap-dropdown.js"></script>
    </body>
</html>
