<style type="text/css">
    body {
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    #perfil {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
        -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
        box-shadow: 0 1px 2px rgba(0,0,0,.05);
    }

    #perfil img {
        width: 310px;
    }

    #perfil #title h2 {
        width: 200px;
    }

    #perfil #action-btns {
        margin-left:40px;
        margin-top:15px;
    }

</style>

<div class="container">
    <section id="perfil">
        <head>
            <section id="title" class="row-fluid">
                <span class="span7"><h2 class="form-createaccount-heading">My Account</h2></span>
                <span class="span5">
                    <div id="action-btns" class="btn-group">
                        <a class="btn btn-primary" href="#"><i class="icon-edit icon-white"></i> Edit</a>
                        <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= $this->url('access-account-edit') ?>"><i class="icon-user"></i> Edit Perfil</a></li>
                            <li><a href="<?= $this->url('access-accountpassword-edit') ?>"><i class="icon-lock"></i> Change Password</a></li>
                        </ul>
                    </div>
                </span>
            </section>
            <img class="img-polaroid" src="<?= $user->getPhoto() ?>" />
        </head>
        <article>
            <h3>Fullname :</h3>
            <p><?= $user->getFullname() ?></p>
            <h3>E-mail :</h3>
            <p><?= $user->getEmail() ?></p>
            <h3>Member since: </h3>
            <p><?= $user->getCreatedAtBR() ?></p>
        </article>
    </section>
</div>


