<style type="text/css">
    body {
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    #perfil {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
        -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
        box-shadow: 0 1px 2px rgba(0,0,0,.05);
    }

    #perfil img {
        width: 310px;
    }

    #perfil #title h2 {
        width: 200px;
    }

    #perfil #title a {
        margin-top:15px;
    }

</style>

<div class="container">
    <section id="perfil">
        <head>
            <section id="title" class="row-fluid">
                <span class="span10"><h2 class="form-createaccount-heading">My Account</h2></span>
                <span class="span2"><a href="<?= $this->url('access-account-edit') ?>" class="btn btn-primary">Edit</a></span>
            </section>
            <img class="img-polaroid" src="<?= $user->getPhoto() ?>" />
        </head>
        <article>
            <h3>Fullname :</h3>
            <p><?= $user->getFullname() ?></p>
            <h3>E-mail :</h3>
            <p><?= $user->getEmail() ?></p>
            <h3>Member since: </h3>
            <p><?= $user->getCreatedAtBR() ?></p>
        </article>
    </section>
</div>


